// @ts-nocheck
import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { z } from 'zod'

// POST /api/orders/pos — staff-side till: rings up a face-to-face sale into
// the same `orders` table online/guest/WhatsApp orders use, tagged
// source: 'pos'. Unlike online checkout, food is handed over immediately,
// so the order is created already 'collected' and paid.
const posOrderSchema = z.object({
  van_id: z.string().uuid(),
  payment_method: z.enum(['cash_at_van', 'card_at_van']),
  customer_name: z.string().optional(),
  served_by: z.string().optional(),
  items: z.array(z.object({
    menu_item_id: z.string().uuid(),
    name: z.string(),
    price: z.number(),
    quantity: z.number().int().positive(),
    item_total: z.number(),
  })).min(1),
})

export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await req.json().catch(() => ({}))
  const parsed = posOrderSchema.safeParse(body)
  if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 })
  const { van_id, payment_method, customer_name, served_by, items } = parsed.data

  // Confirm this van belongs to the signed-in staff/owner before selling
  // against it — RLS enforces this too, but a clear 403 beats a cryptic
  // policy-violation error.
  const { data: myVans } = await supabase.rpc('my_van_ids')
  const allowedVanIds = (myVans ?? []).map((v: any) => (typeof v === 'string' ? v : v.my_van_ids ?? v.id))
  if (!allowedVanIds.includes(van_id)) {
    return NextResponse.json({ error: 'Not your van' }, { status: 403 })
  }

  const subtotal = items.reduce((sum, item) => sum + item.item_total, 0)
  const total = subtotal

  const now = new Date().toISOString()
  const { data: order, error } = await supabase
    .from('orders')
    .insert({
      van_id,
      payment_method,
      subtotal,
      total,
      guest_name: customer_name?.trim() || 'Walk-in customer',
      notes: served_by?.trim() ? `Served by ${served_by.trim()}` : null,
      status: 'collected',
      collected_at: now,
      accepted_at: now,
      source: 'pos',
      order_number: '', // auto-generated by trigger
    })
    .select()
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  const orderItems = items.map(item => ({
    order_id: order.id,
    menu_item_id: item.menu_item_id,
    name: item.name,
    price: item.price,
    quantity: item.quantity,
    item_total: item.item_total,
  }))
  const { error: itemsErr } = await supabase.from('order_items').insert(orderItems)
  if (itemsErr) return NextResponse.json({ error: itemsErr.message }, { status: 500 })

  return NextResponse.json(order, { status: 201 })
}
