import clsx from 'clsx'
import { Check, CircleDashed, Minus, X } from 'lucide-react'
import type { CompanyAnalysis } from '@/lib/analysis/build'
import { toSnapshot } from '@/lib/analysis/snapshot'
import { DEMO_UNIVERSE } from '@/lib/providers/demo'
import { currencySymbol, fmtPct, fmtShares } from '@/lib/format'
import { Section, Stat, Callout } from '@/components/ui/section'
import { SourceTag } from '@/components/ui/source-tag'
import { ScoreRing } from '@/components/ui/score'
import { AnnualChart } from '@/components/charts/annual-chart'
import type { CriterionStatus } from '@/lib/scoring/frameworks'
import { IndicatorList, Pill, Unavailable } from './primitives'
import { Competitors as CompetitorTable } from './competitors'

const MOAT_LABEL: Record<string, string> = {
  brand: 'Brand',
  network_effects: 'Network effects',
  switching_costs: 'Switching costs',
  cost_advantage: 'Cost advantage',
  intellectual_property: 'Intellectual property / patents',
  distribution: 'Distribution',
  scale: 'Economies of scale',
  ecosystem: 'Customer ecosystem',
  data: 'Data advantage',
  regulatory: 'Regulatory advantage',
}

export function Moat({ a }: { a: CompanyAnalysis }) {
  const q = a.dataset.qualitative
  const c = a.categories.find((x) => x.key === 'business_quality')!
  return (
    <Section
      id="moat"
      kicker="Economic moat"
      title="Does it have a durable competitive advantage?"
      description="Moat score = 60% evidenced qualitative rubric + 40% quantitative proxies (ROIC persistence, gross-margin stability, pricing power)."
      actions={a.moat.rating && <Pill tone={(a.moat.score ?? 0) >= 72 ? 'pos' : (a.moat.score ?? 0) >= 55 ? 'neu' : 'neg'}>Moat: {a.moat.rating}</Pill>}
    >
      <div className="grid gap-6 lg:grid-cols-[200px_1fr]">
        <div className="flex flex-col items-center gap-3">
          <ScoreRing score={a.moat.score} label="Moat score" sub={a.moat.rating ?? undefined} />
          <div className="text-center text-xs text-fg-3">
            Qualitative {a.moat.qualitative ?? '—'} · Quantitative {a.moat.quantitative ?? '—'}
          </div>
          <div className="text-center text-[11px] text-fg-4">None &lt;35 · Narrow &lt;55 · Moderate &lt;72 · Wide &lt;92 · Exceptional</div>
        </div>
        {q ? (
          <div className="scrollbar-thin overflow-x-auto">
            <table className="tbl">
              <thead>
                <tr>
                  <th>Moat source</th>
                  <th>Strength</th>
                  <th className="min-w-[320px]">Evidence</th>
                </tr>
              </thead>
              <tbody>
                {q.moat.map((m) => (
                  <tr key={m.source}>
                    <td className="text-fg">{MOAT_LABEL[m.source]}</td>
                    <td>
                      <span className="inline-flex gap-0.5" aria-label={`${m.strength} of 3`}>
                        {[1, 2, 3].map((n) => (
                          <span key={n} className={clsx('h-2 w-5 rounded-sm', n <= m.strength ? 'bg-accent' : 'bg-ink-700')} />
                        ))}
                      </span>
                      <span className="ml-2 text-xs text-fg-3">{['None', 'Weak', 'Moderate', 'Strong'][m.strength]}</span>
                    </td>
                    <td className="whitespace-normal text-xs text-fg-2">{m.evidence}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div className="mt-2 flex items-center gap-2 text-xs text-fg-4">
              Editorial inputs with evidence, reviewed by an analyst — not generated by AI at request time. <SourceTag source={a.dataset.sources[q.sourceId]} />
            </div>
          </div>
        ) : (
          <Unavailable title="Qualitative moat assessment">No reviewed editorial assessment exists for this company. Only the quantitative moat proxies are scored.</Unavailable>
        )}
      </div>
      <div className="mt-6">
        <IndicatorList a={a} indicators={c.indicators} />
      </div>
    </Section>
  )
}

export function Management({ a }: { a: CompanyAnalysis }) {
  const c = a.categories.find((x) => x.key === 'management')!
  const d = a.dilution
  const sym = currencySymbol(a.dataset.profile.currency)
  const dilTone = d.rate5 === null ? 'default' : d.rate5 < -0.5 ? 'pos' : d.rate5 <= 1 ? 'neu' : 'neg'
  const dilWord = d.rate5 === null ? 'Data unavailable' : d.rate5 < -0.5 ? 'Net buybacks' : d.rate5 <= 1 ? 'Stable' : 'Significant dilution'
  return (
    <Section id="management" kicker={`Management & capital allocation · Capital Allocation Score ${c.score ?? '—'}/100`} title="Is management allocating capital effectively?" description="Measured from reported data only — no unsupported opinions about individuals.">
      <div className="grid gap-6 lg:grid-cols-2">
        <div>
          <div className="mb-3 flex items-center justify-between">
            <h3 className="text-sm font-semibold text-fg" id="dilution">
              Share dilution
            </h3>
            <Pill tone={dilTone}>{dilWord}</Pill>
          </div>
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <Stat label="Today" value={fmtShares(d.now)} />
            <Stat label="1 yr ago" value={fmtShares(d.y1)} sub={fmtPct(d.rate1, 1, true) + '/yr'} />
            <Stat label="5 yrs ago" value={fmtShares(d.y5)} sub={fmtPct(d.rate5, 1, true) + '/yr'} />
            <Stat label="10 yrs ago" value={fmtShares(d.y10)} sub={fmtPct(d.rate10, 1, true) + '/yr'} />
          </div>
          <div className="mt-4">
            <AnnualChart
              title="Diluted shares outstanding"
              format="shares"
              sym={sym}
              data={a.dataset.annual.map((y) => ({ label: `FY${String(y.fiscalYear).slice(2)}`, shares: y.sharesDiluted }))}
              series={[{ key: 'shares', label: 'Diluted shares', color: '#9085e9', kind: 'bar' }]}
              height={200}
            />
          </div>
        </div>
        <div className="space-y-3">
          <h3 className="text-sm font-semibold text-fg">Ownership, insiders & short interest</h3>
          <Unavailable title="Insider activity (Form 4)">
            Requires parsed Form 4 filings. Insider sales are shown as context only — executives sell for many reasons (diversification, tax, planned 10b5-1 sales).{' '}
            {a.dataset.filings.find((f) => f.form === 'Form 4') && (
              <a className="text-accent hover:underline" href={a.dataset.filings.find((f) => f.form === 'Form 4')!.url} target="_blank" rel="noopener noreferrer">
                View Form 4 filings on EDGAR →
              </a>
            )}
          </Unavailable>
          <Unavailable title="Institutional ownership (13F)">Largest holders and changes require 13F data from a provider. Shown as context, not as a buy/sell signal.</Unavailable>
          <Unavailable title="Short interest">Short % of float, days to cover and trend require exchange short-interest data.</Unavailable>
          <Unavailable title="Executive compensation">Parsed from the DEF 14A proxy statement once filings analysis is connected.</Unavailable>
        </div>
      </div>
      <div className="mt-6">
        <IndicatorList a={a} indicators={c.indicators} />
      </div>
    </Section>
  )
}

export function Dividend({ a }: { a: CompanyAnalysis }) {
  const c = a.categories.find((x) => x.key === 'dividend')!
  const L = a.fp.latest
  const sym = currencySymbol(a.dataset.profile.currency)
  return (
    <Section
      id="dividend"
      kicker={`Dividend analysis · Dividend Safety Score ${a.dividendSafety ?? '—'}/100`}
      title="Is the dividend sustainable?"
      description="Dividend Safety blends earnings and FCF payout, balance-sheet strength and FCF consistency. Yield is scored separately — a high yield is not the same as a safe one."
    >
      <div className="grid grid-cols-2 gap-3 md:grid-cols-5">
        <Stat label="Dividend yield" value={fmtPct(a.valuation.dividendYield, 2)} />
        <Stat label="Payout ratio" value={fmtPct(L.payoutRatio)} />
        <Stat label="FCF payout ratio" value={fmtPct(L.fcfPayoutRatio)} />
        <Stat label="DPS growth (5-yr)" value={fmtPct(a.fp.growth.dividend.y5, 1, true)} />
        <Stat label="Years paid (in dataset)" value={`${a.dataset.annual.filter((y) => (y.dividendsPaid ?? 0) > 0).length}`} />
      </div>
      <div className="mt-5 grid gap-6 lg:grid-cols-2">
        <AnnualChart
          title="Dividend per share"
          format="price"
          sym={sym}
          data={a.dataset.annual.map((y) => ({ label: `FY${String(y.fiscalYear).slice(2)}`, dps: y.dividendPerShare }))}
          series={[{ key: 'dps', label: 'Dividend per share', color: '#199e70', kind: 'bar' }]}
          height={200}
        />
        <IndicatorList a={a} indicators={c.indicators} />
      </div>
    </Section>
  )
}

export function CompetitorSection({ a }: { a: CompanyAnalysis }) {
  const ds = a.dataset
  const self = { ...toSnapshot(a), self: true as const, iqs: a.overall.score }
  return (
    <Section
      id="competitors"
      kicker="Competitor analysis"
      title="How does it compare with competitors?"
      description="Default peers span the segments the company competes in. Toggle companies to change the comparison."
      actions={ds.peers[0] && <SourceTag source={ds.sources[ds.peers[0].sourceId]} />}
    >
      {ds.peers.length || ds.mode === 'demo' ? (
        <CompetitorTable self={self} peers={ds.peers} universe={DEMO_UNIVERSE} sym={currencySymbol(ds.profile.currency)} />
      ) : (
        <Unavailable title="Peer data">Automatic peer discovery requires a provider peers endpoint.</Unavailable>
      )}
    </Section>
  )
}

export function Industry({ a }: { a: CompanyAnalysis }) {
  const q = a.dataset.qualitative
  if (!q)
    return (
      <Section id="industry" kicker="Industry, macro & economic cycle" title="Industry analysis">
        <Unavailable title="Industry analysis">Requires a reviewed editorial profile.</Unavailable>
      </Section>
    )
  const cycleTone = q.cyclicality === 'defensive' ? 'pos' : q.cyclicality === 'moderately_cyclical' ? 'neu' : 'neg'
  return (
    <Section id="industry" kicker="Industry, macro & economic cycle" title="The industry it competes in" actions={<SourceTag source={a.dataset.sources[q.sourceId]} />}>
      <p className="max-w-4xl text-sm text-fg-2">{q.industry.overview}</p>
      <div className="mt-5 grid gap-5 lg:grid-cols-3">
        <div>
          <h3 className="mb-2 text-sm font-semibold text-fg">Major trends</h3>
          <ul className="list-disc space-y-1 pl-5 text-sm text-fg-2">
            {q.industry.trends.map((t) => (
              <li key={t}>{t}</li>
            ))}
          </ul>
        </div>
        <div className="space-y-3 text-sm">
          {(
            [
              ['Barriers to entry', q.industry.barriers],
              ['Regulation', q.industry.regulation],
              ['Market concentration', q.industry.concentration],
            ] as const
          ).map(([k, v]) => (
            <div key={k}>
              <div className="label">{k}</div>
              <p className="mt-0.5 text-fg-2">{v}</p>
            </div>
          ))}
        </div>
        <div className="grid gap-3">
          <div>
            <h3 className="mb-1 text-sm font-semibold text-pos">Potential opportunities</h3>
            <ul className="list-disc space-y-1 pl-5 text-sm text-fg-2">
              {q.industry.opportunities.map((t) => (
                <li key={t}>{t}</li>
              ))}
            </ul>
          </div>
          <div>
            <h3 className="mb-1 text-sm font-semibold text-neg">Potential threats</h3>
            <ul className="list-disc space-y-1 pl-5 text-sm text-fg-2">
              {q.industry.threats.map((t) => (
                <li key={t}>{t}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>
      <div className="mt-6 grid gap-5 lg:grid-cols-2">
        <div id="macro">
          <h3 className="mb-2 text-sm font-semibold text-fg">Macroeconomic sensitivities (material ones only)</h3>
          <div className="scrollbar-thin overflow-x-auto">
          <table className="tbl">
            <tbody>
              {q.macroSensitivities.map((m) => (
                <tr key={m.factor}>
                  <td className="text-fg">{m.factor}</td>
                  <td>
                    <Pill tone={m.relevance === 'high' ? 'neg' : m.relevance === 'medium' ? 'neu' : 'default'}>{m.relevance}</Pill>
                  </td>
                  <td className="whitespace-normal text-xs text-fg-2">{m.explanation}</td>
                </tr>
              ))}
            </tbody>
          </table>
          </div>
          <p className="mt-2 text-xs text-fg-4">Live macro series (rates, inflation, GDP) connect via the FRED adapter — planned.</p>
        </div>
        <div id="cycle">
          <h3 className="mb-2 flex items-center gap-2 text-sm font-semibold text-fg">
            Economic cycle <Pill tone={cycleTone}>{q.cyclicality.replace('_', ' ')}</Pill>
          </h3>
          <p className="text-sm text-fg-2">{q.cyclicalityReason}</p>
        </div>
      </div>
    </Section>
  )
}

const STATUS: Record<CriterionStatus, { Icon: typeof Check; cls: string; word: string }> = {
  pass: { Icon: Check, cls: 'text-pos', word: 'Pass' },
  partial: { Icon: Minus, cls: 'text-neu', word: 'Partial' },
  fail: { Icon: X, cls: 'text-neg', word: 'Fail' },
  na: { Icon: CircleDashed, cls: 'text-fg-3', word: 'Not applied' },
  unavailable: { Icon: CircleDashed, cls: 'text-fg-4', word: 'No data' },
}

export function Frameworks({ a }: { a: CompanyAnalysis }) {
  return (
    <Section
      id="frameworks"
      kicker="Investor strategy analysis"
      title="How would different investing frameworks view it?"
      description="Each framework is inspired by concepts from published investing literature, applied mechanically. None implies endorsement by the named investor."
    >
      <div className="grid gap-4 xl:grid-cols-2">
        {a.frameworks.map((f) => (
          <article key={f.key} id={`fw-${f.key}`} className="rounded-lg border border-ink-700 bg-ink-900/40 p-4">
            <header className="flex items-start justify-between gap-3">
              <div>
                <h3 className="font-semibold text-fg">{f.name}</h3>
                <p className="mt-1 text-xs text-fg-3">{f.summary}</p>
              </div>
              <div className="text-right">
                <div className="num text-2xl font-semibold text-fg">
                  {f.score ?? '—'}
                  <span className="text-xs text-fg-4">/100</span>
                </div>
                <div className="text-[11px] text-fg-3">{f.scoreLabel}</div>
                {f.classicScore !== undefined && f.classicScore !== f.score && <div className="text-[11px] text-fg-4">Classic (unadjusted): {f.classicScore}</div>}
              </div>
            </header>
            {f.classification && (
              <div className="mt-3 rounded-md border border-accent/30 bg-accent-soft p-2 text-sm">
                <span className="font-semibold text-accent">Lynch category: {f.classification.label}</span>
                <span className="block text-xs text-fg-2">{f.classification.reason}</span>
              </div>
            )}
            <ul className="mt-3 divide-y divide-ink-750">
              {f.criteria.map((c) => {
                const S = STATUS[c.status]
                return (
                  <li key={c.label} className="flex gap-3 py-2 text-sm">
                    <S.Icon className={clsx('mt-0.5 h-4 w-4 shrink-0', S.cls)} aria-label={S.word} />
                    <div className="min-w-0 flex-1">
                      <div className="flex flex-wrap justify-between gap-x-3">
                        <span className="text-fg-2">{c.label}</span>
                        <span className="num text-fg">{c.value}</span>
                      </div>
                      {c.note && <div className="text-xs text-fg-4">{c.note}</div>}
                    </div>
                  </li>
                )
              })}
            </ul>
            {f.figures && (
              <div className="mt-2 flex flex-wrap gap-2">
                {f.figures.map((x) => (
                  <Pill key={x.label}>
                    {x.label}: <span className="num text-fg">{x.value}</span>
                  </Pill>
                ))}
              </div>
            )}
            {f.caveats.map((cv) => (
              <p key={cv} className="mt-2 text-xs text-fg-4">
                {cv}
              </p>
            ))}
          </article>
        ))}
      </div>
      <div className="mt-4">
        <Callout>Frameworks are shown alongside — not inside — the Investment Quality Score. Choose an investor mode above to re-weight the main score towards a style.</Callout>
      </div>
    </Section>
  )
}
