import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { z } from 'zod'

const orderSchema = z.object({
  van_id: z.string().uuid(),
  stop_id: z.string().uuid().optional(),
  payment_method: z.enum(['card_online', 'cash_at_van', 'card_at_van']),
  items: z.array(z.object({
    menu_item_id: z.string().uuid(),
    name: z.string(),
    price: z.number(),
    quantity: z.number().int().positive(),
    options: z.record(z.string()).optional(),
    item_total: z.number(),
  })).min(1),
  notes: z.string().optional(),
  collection_time: z.string().optional(),
})

export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await req.json()
  const parsed = orderSchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 })
  }
  const { van_id, stop_id, payment_method, items, notes, collection_time } = parsed.data

  // Get customer record
  const { data: userData } = await supabase.from('users').select('id').eq('auth_id', user.id).single()
  const { data: customer } = await supabase.from('customers').select('id').eq('user_id', userData?.id).single()

  if (!customer) return NextResponse.json({ error: 'Customer profile not found' }, { status: 404 })

  const subtotal = items.reduce((sum, item) => sum + item.item_total, 0)
  const total = subtotal // VAT handled separately if enabled

  const { data: order, error } = await supabase
    .from('orders')
    .insert({
      customer_id: customer.id,
      van_id,
      stop_id,
      payment_method,
      subtotal,
      total,
      notes,
      collection_time,
      order_number: '', // auto-generated by trigger
    })
    .select()
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Insert order items
  const orderItems = items.map(item => ({
    order_id: order.id,
    menu_item_id: item.menu_item_id,
    name: item.name,
    price: item.price,
    quantity: item.quantity,
    options: item.options ?? null,
    item_total: item.item_total,
  }))

  await supabase.from('order_items').insert(orderItems)

  // Send notification to van owner (via edge function)
  await supabase.functions.invoke('send-notification', {
    body: {
      type: 'new_order',
      order_id: order.id,
      van_id,
    },
  })

  return NextResponse.json(order, { status: 201 })
}

export async function GET(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const van_id = searchParams.get('van_id')

  let query = supabase
    .from('orders')
    .select(`*, order_items(*), customers(*, users(full_name, phone)), route_stops(name, postcode)`)
    .order('created_at', { ascending: false })

  if (van_id) query = query.eq('van_id', van_id)

  const { data, error } = await query.limit(100)
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data)
}
