import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { getProduceVideoQueue } from '@/lib/queue/queues'

export async function POST(_request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: topic, error } = await supabase
    .from('yt_topics')
    .select('id, channel_id, schedule_id, yt_channels!inner(user_id)')
    .eq('id', id)
    .single()
  if (error || !topic) return NextResponse.json({ error: 'Topic not found' }, { status: 404 })
  const channel = Array.isArray(topic.yt_channels) ? topic.yt_channels[0] : topic.yt_channels
  if (channel.user_id !== user.id) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  if (!topic.schedule_id) return NextResponse.json({ error: 'Topic has no schedule slot to regenerate into' }, { status: 400 })

  await supabase.from('yt_topics').update({ status: 'rejected', rejected_reason: 'Regenerated by user' }).eq('id', id)
  const { data: schedule } = await supabase.from('yt_schedules').select('video_kind').eq('id', topic.schedule_id).single()
  await supabase.from('yt_schedules').update({ status: 'planned', video_id: null }).eq('id', topic.schedule_id)

  await getProduceVideoQueue().add(
    'produce-video',
    { kind: 'produce', channelId: topic.channel_id, scheduleId: topic.schedule_id, videoKind: schedule!.video_kind },
    { jobId: `produce-${topic.schedule_id}-${Date.now()}` }
  )

  return NextResponse.json({ ok: true })
}
