import { demoDataset } from '@/lib/providers/demo'
import { buildAnalysis } from '@/lib/analysis/build'
import { MODE_INFO, MODE_WEIGHTS } from '@/lib/scoring/weights'
import { CATEGORY_LABELS, CATEGORY_ORDER } from '@/lib/scoring/types'
import { Callout } from '@/components/ui/section'

export const metadata = { title: 'Scoring methodology' }

/**
 * Rendered from the scoring engine itself (indicator bases and weight tables),
 * so the published methodology cannot drift from the code.
 */
export default function MethodologyPage() {
  const a = buildAnalysis(demoDataset('AAPL')!)!
  const modes = Object.keys(MODE_WEIGHTS) as (keyof typeof MODE_WEIGHTS)[]
  return (
    <div className="mx-auto max-w-5xl space-y-8 px-4 py-12 sm:px-6">
      <header>
        <div className="label">Methodology</div>
        <h1 className="mt-1 text-3xl font-semibold tracking-tight text-fg">How the Investment Quality Score works</h1>
        <p className="mt-3 text-fg-2">
          The score answers one question: <em>how strong are the positive and negative signals surrounding this company as a potential long-term investment?</em> It is a structured weighing of evidence — not
          a probability that the share price will rise, and not a recommendation.
        </p>
      </header>

      <section className="card card-pad space-y-3 text-sm text-fg-2">
        <h2 className="text-lg font-semibold text-fg">The calculation</h2>
        <ol className="list-decimal space-y-2 pl-5">
          <li>Financial statements, prices and estimates are loaded through a provider adapter. Every figure keeps its source, reporting period and update date.</li>
          <li>Ratios (ROIC, margins, P/E, PEG, FCF yield, Debt/EBITDA, CAGR…) are computed in code — never by an AI model.</li>
          <li>
            Each <strong className="text-fg">indicator</strong> maps its value onto 0–100 using a published piecewise-linear curve. 50 is neutral. Ratings: ≥85 strong positive, ≥65 positive, ≥45 neutral, ≥25
            negative, below 25 strong negative.
          </li>
          <li>
            A <strong className="text-fg">category score</strong> is the weighted average of its indicators that have data. Missing data is excluded — never scored as zero — and lowers Data Confidence instead.
          </li>
          <li>
            The <strong className="text-fg">overall score</strong> is the weighted average of categories, with weights set by the investor mode and renormalised over categories that have data. Equivalently:
            start at 50 and add each indicator’s points — the “Why?” panel on every company page shows this breakdown.
          </li>
          <li>Qualitative inputs (moat sources, risk factors) are structured analyst assessments with written evidence, clearly marked as editorial. They are not generated by AI at request time.</li>
        </ol>
        <Callout>Technical and sentiment inputs are capped at 5% combined in the default mode, so short-term price action cannot dominate a long-term assessment.</Callout>
      </section>

      <section className="card card-pad">
        <h2 className="mb-3 text-lg font-semibold text-fg">Category weights by investor mode (%)</h2>
        <div className="scrollbar-thin overflow-x-auto">
          <table className="tbl">
            <thead>
              <tr>
                <th>Category</th>
                {modes.map((m) => (
                  <th key={m} className="text-right">
                    {MODE_INFO[m].label.replace(' investor', '').replace(' (default)', '')}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {CATEGORY_ORDER.map((k) => (
                <tr key={k}>
                  <td className="text-fg">{CATEGORY_LABELS[k]}</td>
                  {modes.map((m) => (
                    <td key={m} className="num text-right">
                      {MODE_WEIGHTS[m][k] || '—'}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="mt-2 text-xs text-fg-4">Users can also build a custom strategy with their own weights.</p>
      </section>

      <section className="card card-pad">
        <h2 className="mb-1 text-lg font-semibold text-fg">Indicator reference</h2>
        <p className="mb-4 text-sm text-fg-3">Every indicator, its category, default weight within the category, and exactly how it is scored.</p>
        {CATEGORY_ORDER.map((k) => {
          const list = a.indicators.filter((i) => i.category === k && !i.id.startsWith('risk.q.'))
          const qual = a.indicators.filter((i) => i.category === k && i.id.startsWith('risk.q.'))
          return (
            <div key={k} className="mb-6">
              <h3 className="mb-2 font-semibold text-fg">{CATEGORY_LABELS[k]}</h3>
              <div className="scrollbar-thin overflow-x-auto">
                <table className="tbl">
                  <tbody>
                    {list.map((i) => (
                      <tr key={i.id}>
                        <td className="w-64 whitespace-normal align-top text-fg">
                          {i.label}
                          {i.qualitative && <span className="ml-1 text-xs text-fg-4">(editorial)</span>}
                        </td>
                        <td className="num w-12 align-top">×{i.weight}</td>
                        <td className="whitespace-normal align-top text-xs text-fg-3">{i.basis}</td>
                      </tr>
                    ))}
                    {qual.length > 0 && (
                      <tr>
                        <td className="whitespace-normal align-top text-fg">Editorial risk factors ({qual.length})</td>
                        <td className="num align-top">×0.6 each</td>
                        <td className="whitespace-normal align-top text-xs text-fg-3">{qual[0].basis} Factors: {qual.map((q) => q.label).join(', ')}.</td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          )
        })}
      </section>

      <section className="card card-pad space-y-2 text-sm text-fg-2">
        <h2 className="text-lg font-semibold text-fg">Data Confidence</h2>
        <p>
          Metric coverage 40% · data freshness 20% · source reliability 25% (filing 100, provider 90, estimate/editorial 70, demo 35) · historical depth 15%. Cross-source consensus will be added once two
          independent providers are connected.
        </p>
      </section>

      <section className="card card-pad space-y-2 text-sm text-fg-2">
        <h2 className="text-lg font-semibold text-fg">Is the score predictive? (Backtesting)</h2>
        <p>
          Not yet known — and we say so. The backtesting module will recompute point-in-time scores (using filings only from their filing dates, and a survivorship-bias-free universe including delisted
          companies), bucket them 80–100 / 60–79 / 40–59 / &lt;40, and measure forward 1-, 3- and 5-year returns against benchmarks. Until then, treat the score as an organised summary of evidence.
        </p>
      </section>
    </div>
  )
}
